variables:
  CI: true
trigger:
  - master
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        fetchDepth: 10
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
      - script: make -j"$(cat /proc/cpuinfo | grep -e '^processor' | wc -l)"
        displayName: Build
      - script: make -j"$(cat /proc/cpuinfo | grep -e '^processor' | wc -l)" check
        displayName: Check
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 10
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
      - script: |
          make
          make storybook
        displayName: Build
      - script: make check
        displayName: Check
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    steps:
      - checkout: self
        fetchDepth: 10
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
      - script: make -j"$(sysctl hw.logicalcpu | cut -d' ' -f2)"
        displayName: Build
      - script: make -j"$(sysctl hw.logicalcpu | cut -d' ' -f2)" check
        displayName: Check
