variables:
  NPM_CONFIG_CACHE: $(Pipeline.Workspace)/.npm
trigger:
  - master
pool:
  vmImage: 'ubuntu-16.04'
steps:
  - checkout: self
    fetchDepth: 1
  - task: CacheBeta@0
    inputs:
      key: $(Build.SourcesDirectory)/package-lock.json
      path: $(NPM_CONFIG_CACHE)
    displayName: Cache npm
  - script: make
    displayName: Build
  - script: make storybook
    displayName: Build storybook
  - script: make check
    displayName: Check
  - script: sccache --show-stats
    displayName: Show sccache stats
    condition: eq(variables.CACHE_RESTORED_SCCACHE, 'true')
